config/routes.rb
Rails.application.routes.draw do

  root :to => 'projects#index'

  resources :users

  resources :projects do
    resources :funds
    resources :comments
  end

  resources :rewards


  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/fund.rb
class Fund < ActiveRecord::Base
  belongs_to :user
  belongs_to :reward
  has_one :project, through: :reward
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :rewards
  has_many :funds, through: :rewards
  has_many :comments

  accepts_nested_attributes_for :rewards, reject_if: :all_blank, allow_destroy: true

  validates :description, :title, presence: true
  validates :goal, numericality: {only_integer: true}

end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :project
  has_many :funds
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  has_many :funds
  has_many :projects
  has_many :comments
  has_many :rewards, through: :funds
  has_many :backed_projects, through: :funds, source: "project"

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes["password"] }
  validates :password, confirmation: true, if: -> { new_record? || changes["password"] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes["password"] }

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include CanCan::ControllerAdditions
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @project = Project.find(params[:project_id])
    @comment = @project.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      respond_to do |format|
        format.html do
          redirect_to project_path(@project), notice: "Thank you for commenting this project!"
        end
        format.js
      end
    else
      redirect_to project_path(@project), notice: "Something went wrong, comment not saved"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:title, :body)
  end
end

app/controllers/funds_controller.rb
class FundsController < ApplicationController

  def create
    @project = Project.find(params[:project_id])
    @fund = @project.funds.build(fund_params)
    @fund.user = current_user
    @project_rewards = @project.rewards
    @fund.reward = @project_rewards[@project_rewards.length-1]
    @project_rewards[0...@project_rewards.length-1].each do |reward|
      if (@fund.amount >= reward.min_amount) && (@fund.amount <= reward.max_amount)
        @fund.reward = reward
      end
    end

    if @fund.save
      redirect_to project_path(@project), notice: "Thank you for funding this project!"
    else
      redirect_to project_path(@project), notice: "Something went wrong, fund not saved"
    end
  end

  private
  def fund_params
    params.require(:fund).permit(:amount)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    new_reward = Reward.new(title: "Gratitude", description: "Thanks for the donation",
      min_amount: 0, max_amount: @project.goal)
    @project.rewards.push(new_reward)

    if @project.save
      redirect_to projects_url
    else
      redirect_to new_project_path
    end
  end

  def show
    @project = Project.find(params[:id])
    @project_owner = @project.user
    @project_rewards = @project.rewards
    @times_earned = {}
    @project_rewards.each do |reward|
      @times_earned[reward] = Fund.where(reward_id: reward.id).count

    end
    @comments = @project.comments.sort_by{|comment| comment.created_at}.reverse
    @sum_of_funds = @project.funds.sum(:amount)
    @amount_needed = @project.goal - @sum_of_funds
    if current_user
      @fund = @project.funds.build
      @comment = @project.comments.build
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(project_params)
      redirect_to project_path(@project)
    else
      redirect_to edit_project_path(@project)
    end

  end

  private
  def project_params
    params.require(:project).permit(:title, :description, :goal, :end_date,
    rewards_attributes: [:title, :description, :min_amount, :max_amount, :_destroy])
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  # app/controllers/user_sessions_controller.rb
  skip_before_action :require_login, except: [:destroy]
  
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(projects_path, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
   @user = User.new(user_params)

   respond_to do |format|
     if @user.save
       auto_login(@user)
       format.html { redirect_to projects_path, notice: 'User was successfully created.' }
       format.json { render :show, status: :created, location: @user }
     else
       format.html { render :new }
       format.json { render json: @user.errors, status: :unprocessable_entity }
     end
   end
  end

  def show
    @user_id = params[:id]
    @user = User.find(params[:id])
    @user_projects = Project.where(user_id: @user_id)
    @funds_for_projects = {}
    @amount_to_go = {}
    @user_projects.each do |project|
      @funds_for_projects[project] = project.funds.sum(:amount)
      @amount_to_go[project] = project.goal - @funds_for_projects[project]

    end

    @backed_projects = @user.backed_projects.uniq

    @earned_rewards = @user.rewards


  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class = "comment">
  <strong><%= comment.title %></strong>
  <br>
  <%= comment.body %>
  <br>
  <em> by <%= comment.user.email %></em>
  <br>
  Added on: <%= comment.created_at %>
</div>

app/views/comments/create.js.erb
$('#comments-container').prepend('<%= j render @comment %>');
$('#comment_title').val('');
$('#comment_body').val('');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css">
</head>

  <body>
    <div id="nav"><br>

      <div class="logo-wrapper hide-for-small-only">
        <div class="logo">
          <a href='http://localhost:3000/'><img src='http://s11.postimg.org/tmna0gw8v/cf_logo.png' border='0' alt="cf logo" /></a>
        </div>
      </div>

      <% if current_user %>
      <div class="top-bar">
        <div class="top-bar-right">
          <ul class="menu">
            <!-- Insert Logo img src here -->
            <li><%= link_to "Edit Profile", edit_user_path(current_user.id) %></li>
            <li><%= link_to "User Profile", user_path(current_user) %></li>
            <li><%= link_to "Logout", :logout, method: :post %></li>
          </ul>
        </div>

        <div class="top-bar">
          <div class="top-bar-left">
          Logged in as <%= current_user.email %>
          </div>
        </div>

      <% else %>
        <div class="top-bar">
          <div class="top-bar-right">
            <ul class="menu">
        <%= link_to "Login", :login %> |
        <%= link_to "Register", new_user_path %>
      <% end %>
            </ul>
          </div>
        </div>
    <div>
      <p id="notice"><%= flash[:notice] %></p>
      <p id="alert"><%= flash[:alert] %></p>
    </div>

    <div class="main-img">
      <img src='http://s18.postimg.org/t4y71frd5/technology_wallpapers_hd1.png'></img>
    </div>

<%= yield %>


  </body>
</html>

app/views/projects/_project_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id = "error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class = "field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class = "field">
    <%= f.label :goal %>
    <%= f.number_field :goal %>
  </div>

  <div class = "field">
    <%= f.label :end_date %>
    <%= f.date_field :end_date %>
  </div>

  <h2>Rewards</h2>

  <div id="rewards">
    <%= f.fields_for :rewards do |reward_fields| %>
      <%= render 'reward_fields', f: reward_fields %>
    <% end %>

    <div class="links">
      <%= link_to_add_association "Add Reward", f, :rewards %>
    </div>
  </div>

  <div class="submit">
    <%= f.submit %>
  </div>

<% end %>

app/views/projects/_reward_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :min_amount %>
    <%= f.number_field :min_amount %>
  </div>

  <div class="field">
    <%= f.label :max_amount %>
    <%= f.number_field :max_amount %>
  </div>

  <%= link_to_remove_association "Remove reward", f %>
</div>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>
<% if current_user %>
<% if current_user.id == @project.user_id %>
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id = "error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class = "field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class = "field">
    <%= f.label :goal %>
    <%= f.number_field :goal %>
  </div>

  <div class = "field">
    <%= f.label :end_date %>
    <%= f.date_field :end_date %>
  </div>

  <div class="submit">
    <%= f.submit %>
  </div>

<% end %>
<% else %>
  <h3>You can only edit your own projects.</h3>
<% end %>
<% else %>
  <h3>You can only edit your own projects and must be logged in.</h3>
<% end %>

<%= link_to 'Back', project_path(@project) %>

app/views/projects/index.html.erb
<h1>All Projects</h1>

<div id = "projects">
  <% @projects.each do | project | %>
    <div id = "project">
      <a href = '/projects/<%=project.id%>'><%=project.title%></a>
    </div>
  <% end %>
</div>
<div id = "navigation">
  <%= link_to "New Project", new_project_path %>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>
  <% if current_user %>
    <%= render "project_form" %>
  <% else %>
    <p>Log in to create a new project.</p>
  <% end %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class="container">
  <h1>View Project</h1>
  <div class = "info">
    <strong>Title:</strong> <%= @project.title%>
  </div>
  <div class = "info">
    <strong>Description:</strong> <%= @project.description%>
  </div>
  <div class = "info">
    <strong>Goal:</strong> <%= @project.goal%>
  </div>
  <div class = "info">
    <strong>End Date:</strong> <%= @project.end_date%>
  </div>
  <div class = "info">
    <strong>Amount funded:</strong> <%= @sum_of_funds %>
  </div>
  <div class = "info">
    <strong>Amount needed:</strong> <%= @amount_needed %>
  </div>
  <div class = "info">
    <strong>Project Owner:</strong> <%= @project_owner.email %>
  </div>
</div>


<div class="container">
  <% if @project_rewards %>
    <h2>Rewards</h2>
    <% @project_rewards.each do |reward| %>
      <div class = "info">
        <strong>Title:</strong> <%= reward.title %>
      </div>
      <div class = "info">
        <strong>Description:</strong> <%= reward.description %>
      </div>
      <div class = "info">
        <strong>Minimum Amount:</strong> <%= reward.min_amount %>
      </div>
      <div class = "info">
        <strong>Maximum Amount:</strong> <%= reward.max_amount %>
      </div>
      <div class = "info">
        <strong>Times Reward Earned:</strong> <%= @times_earned[reward] %>
      </div>
    </div>
    <br>
    <% end %>
  <% end %>

<% if @comments %>
  <h2>Comments</h2>
  <div id="comments-container">
    <%= render @comments %>
  </div>
<% end %>
<% if current_user %>

  <h2>Make Comment</h2>
    <%= form_for([@project, @comment]) do |f| %>
      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.label :body %>
        <%= f.text_area :body %>
      </div>
      <div class="submit">
        <%= f.submit %>
      </div>
    <% end %>



  <h2>Fund</h2>
    <%= form_for([@project, @fund]) do |f| %>
      <div class="field">
        <%= f.label :amount %>
        <%= f.number_field :amount %>
      </div>
      <div class="submit">
        <%= f.submit %>
    </div>
  <% end %>


<% end %>

<div id = "navigation">
  <%= link_to "Back", projects_path %> | <%= link_to "Edit Project", edit_project_path(@project) %>
</div>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/users/_user_form.html.erb
<%= form_for @user do |f|  %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="password">
  <%= f.label :password %>
  <%= f.password_field :password %>
  </div>

  <div class="password">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  </div>

  <div class="submit">
  <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>All Users List</h1>

<% @users.each do |user| %>
  <div class='user'>
    <%= link_to user.email, user %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'user_form' %>

app/views/users/show.html.erb
<h1><%= @user.email %>

<% if @user_projects.length > 0 %>
  <h2>Owned Projects</h2>

  <% @user_projects.each do | project | %>
    <div class = "info">
      <strong>Title:</strong> <%= link_to project.title, project_path(project) %>
    </div>
    <div class = "info">
      <strong>Description:</strong> <%= project.description %>
    </div>
    <div class = "info">
      <strong>Goal:</strong> <%= project.goal %>
    </div>
    <div class = "info">
      <strong>End Date:</strong> <%= project.end_date %>
    </div>
    <div class = "info">
      <strong>Amount Funded:</strong> <%= @funds_for_projects[project] %>
    </div>
    <div class = "info">
      <strong>Amount Needed:</strong> <%= @amount_to_go[project] %>
    </div>
    <% if current_user == project.user %>
      <%= link_to "Edit Project", edit_project_path(project) %>
    <% end %>
  <% end %>

<% else %>

  <h3>User has no owned projects</h3>

<% end %>



<% if @backed_projects.length > 0 %>
  <h2>Backed Projects</h2>
  <% @backed_projects.each do |backed_project| %>
    <div class = "info">
      <%= link_to backed_project.title, project_path(backed_project) %>
    </div>
  <% end %>

<% else %>

  <h3>User has no backed projects</h3>

<% end %>

<% if @earned_rewards.length > 0 %>
  <h2>Earned Rewards</h2>
  <% @earned_rewards.each do |earned_reward| %>
    <div class = "info">
      <strong>Title:</strong> <%= earned_reward.title %>, for Project: <%= earned_reward.project.title %>
    </div>
  <% end %>

<% else %>

  <h3>User hasn't earned any rewards.</h3>

<% end %>